---

- hosts: localhost
  # connection: local
  tasks:
   #- name: Sending an e-mail using Gmail SMTP server
   - community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: testeteria@gmail.com
        password: Yesterday14
        to: israel <treble123@gmail.com>
        subject: Ansible-report
        body: System has been successfully provisioned.
     delegate_to: localhost


